/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-04-22 07:52:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.meeting;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.GregorianCalendar;
import java.util.Calendar;
import java.util.ArrayList;
import meeting.model.vo.Meeting;
import java.util.List;
import member.model.vo.Member;

public final class meetingList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1618907732456L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1619077691512L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.GregorianCalendar");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("meeting.model.vo.Meeting");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String msg = (String) session.getAttribute("msg");
	if (msg != null)
	session.removeAttribute("msg");
	Member loginMember = (Member) session.getAttribute("loginMember");
	//사용자 쿠키처리
	String saveId = null;
	Cookie[] cookies = request.getCookies();
	if (cookies != null) {
		for (Cookie c : cookies) {
			String name = c.getName();
			String value = c.getValue();
			System.out.println(name + " : " + value);
			if ("saveId".equals(name))
		saveId = value;
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/header.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"boxContainer\">\r\n");
      out.write("\t\t\t\t<table class=\"elementsContainer\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"searchKeyword\" type=\"text\" placeholder=\"Search\" class=\"search\" onkeyup=\"enterkey();\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"material-icons\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/baseline_search_black_24dp.png\"  onclick=\"search();\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/Logo.png\" id=\"Logo\"/></a>\r\n");
      out.write("\t\t\t<div class=\"login\">\r\n");
      out.write("\t\t\t");

				if (loginMember == null) {
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"로그인\" id=\"login_button\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"회원가입\" id=\"signup_button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/enroll';\">\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<table id=\"login\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(loginMember.getName());
      out.write("님, 안녕하세요.</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"button\" value=\"mypage\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/mypage';\" class=\"loginbtn\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"logout\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout';\" class=\"loginbtn\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"loginEnd\"></div>\r\n");
      out.write("\t\t<div id=\"login_frame_wrapper\" >\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<!-- Loginframe 평소에 hide -->\r\n");
      out.write("\t\t<div id=\"login_frame_div\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<div id=\"information_in_image1_wrapper\">\r\n");
      out.write("\t\t\t<h1 id=\"information_in_image1\">지금 바로 원하는 지역의 모임 </h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h1 id=\"information_in_image2\">미플 </h1>\r\n");
      out.write("\t\t\t<h1 id=\"login_count1\">현재 <a id=\"memberCount\"></a>명의 회원이 미플과 함께하고 있어요.</h1>\r\n");
      out.write("\t\t\t<h1 id=\"login_count2\"><a id=\"meetingCount\"></a>개의 모임에 지금 바로참여하세요  :)</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/meet.jpg\" id=\"login_image\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 로그인 포지션-->\r\n");
      out.write("\t\t\t<form id=\"login_form\"\r\n");
      out.write("\t\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/member/login\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"login_closeBtn\" value=\"X\" style=\"float:right;\"/>\r\n");
      out.write("\t\t\t\t\t<h1 style=\"clear:both;\">로그인</h1>\r\n");
      out.write("\t\t\t\t\t<br> \r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"id_input\" id=\"id_input\" placeholder=\"아이디를 입력해주세요.\"");
      out.print(saveId != null ? "value='" + saveId + "'" : "");
      out.write("> <br>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"password_input\" id=\"password_input\" placeholder=\"비밀번호를 입력해주세요.\"> <br> \r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"login_submit\" id=\"login_submit\" value=\"로그인\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div id=\"checkbox_findbox_wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"checkbox_wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"saveid\" id=\"saveid\" ");
      out.print(saveId != null ? "checked" : "");
      out.write(" /> \r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"saveid\" id=\"saveidlabel\">로그인 유지하기</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/find\"><span id=\"find_span\">아이디+비밀번호 찾기</span></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t\t<div class=\"enroll_div\" id=\"enroll_div\"  onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/enroll';\" style=\"clear:both\";>\r\n");
      out.write("\t\t\t\t\t\t미플 회원가입하기\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<ol>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList\">전체</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingEnrollUpdate\">mt:enrollUpdate</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingView\">mt:View</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C1\">음악</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C2\">게임</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C3\">운동</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C4\">요리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C5\">독서</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C6\">재테크</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C7\">자동차</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/board/boardList\">자유게시판</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/board/adminBoardList\">공지사항</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">회원관리</a></li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t");
if(msg!=null){
      out.write("\r\n");
      out.write("\t\t\t\talert(\"");
      out.print(msg);
      out.write("\");\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t$(signup_button).click(function(){\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/member/enroll\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(login_button).click(function() {\r\n");
      out.write("\t\t\t\tvar top = screen.availHeight / 2 - 250;\r\n");
      out.write("\t\t\t\t$(\"#login_frame_div\").attr('style', 'display:flex; top:'+top+'px;');\r\n");
      out.write("\t\t\t\t$(\"#login_frame_wrapper\").attr('style', 'display:flex; top:'+top+'px;');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(id_input.value.length==0){\r\n");
      out.write("\t\t\t\t\t$('#id_input').focus();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$('#password_input').focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(login_closeBtn).click(function(){\r\n");
      out.write("\t\t\t\t$(\"#login_frame_div\").attr('style', 'display:none;');\r\n");
      out.write("\t\t\t\t$(\"#login_frame_wrapper\").attr('style', 'display:none;');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(login_frame_wrapper).click(function(){\r\n");
      out.write("\t\t\t\t$(\"#login_frame_div\").attr('style', 'display:none;');\r\n");
      out.write("\t\t\t\t$(\"#login_frame_wrapper\").attr('style', 'display:none;');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t//총인원과 총모임 ajax\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.print( request.getContextPath());
      out.write("/member/count\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t/* 총인원수 저장 */\r\n");
      out.write("\t\t\t\t\t\tvar memberCount=data;\r\n");
      out.write("\t\t\t\t\t\t$(\"#memberCount\").html(memberCount);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror:function(xhr, status, error){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(xhr, status, error);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.print( request.getContextPath());
      out.write("/member/count\",\r\n");
      out.write("\t\t\t\t\tmethod: \"POST\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tvar meetingCount=data;\r\n");
      out.write("\t\t\t\t\t\t$(\"#meetingCount\").html(meetingCount);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror:function(xhr, status, error){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(xhr, status, error);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//검색창 엔터\r\n");
      out.write("\t\t\tfunction enterkey() {\r\n");
      out.write("\t\t        if (window.event.keyCode == 13) {\r\n");
      out.write("\t\t        \tsearch();\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction search(){\r\n");
      out.write("\t\t\t\tvar $keyword = $(\"#searchKeyword\").val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(/^.{1,}$/.test($keyword)==false){\r\n");
      out.write("\t\t\t\t\t$(\"#searchKeyword\").focus();\r\n");
      out.write("\t\t\t\t\talert(\"검색 키워드를 1글자 이상 입력해주세요\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?search=\"+$keyword;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<section>");
      out.write('\r');
      out.write('\n');

	List<Meeting> list = (List<Meeting>)request.getAttribute("list");
	String location = (String)request.getAttribute("location");
	String category = (String)request.getAttribute("category");
	String search = (String)request.getAttribute("search");
	
	String cName;
	String lName;
	
	if(category.equals("C1")){
		cName="음악";
	}else if(category.equals("C2")){
		cName="게임";
	}else if(category.equals("C3")){
		cName="운동";
	}else if(category.equals("C4")){
		cName="요리";
	}else if(category.equals("C5")){
		cName="독서";
	}else if(category.equals("C6")){
		cName="재테크";
	}else if(category.equals("C7")){
		cName="자동차";
	}else{
		cName="전체";
	}
	
	if(location.equals("L1")){
		lName="서울";
	}else if(location.equals("L2")){
		lName="경기";
	}else if(location.equals("L3")){
		lName="인천";
	}else if(location.equals("L4")){
		lName="대전·충청";
	}else if(location.equals("L5")){
		lName="대구·경북";
	}else if(location.equals("L6")){
		lName="부산·경남";
	}else if(location.equals("L7")){
		lName="울산";
	}else if(location.equals("L8")){
		lName="광주";
	}else{
		lName="전국";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"listWrapper\">\r\n");
      out.write("\t<div id=\"leftWrapper\">\r\n");
      out.write("\t\t<h4>");
      out.print( cName+" > "+lName);
      out.write("</h4>\r\n");
      out.write("\t\t");

			if(search.length()!=0){
		
      out.write("\r\n");
      out.write("\t\t\t<h4>제목 검색 : ");
      out.print(search );
      out.write("</h4>\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=");
      out.print(category);
      out.write("&location=");
      out.print(location);
      out.write("'\">초기화</button>\t\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<h4>지역</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ol>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=");
      out.print(category);
      out.write("&search=");
      out.print(search);
      out.write("\">전국</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=");
      out.print(category);
      out.write("&location=L1&search=");
      out.print(search);
      out.write("\">서울</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=");
      out.print(category);
      out.write("&location=L2&search=");
      out.print(search);
      out.write("\">경기</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=");
      out.print(category);
      out.write("&location=L3&search=");
      out.print(search);
      out.write("\">인천</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=");
      out.print(category);
      out.write("&location=L4&search=");
      out.print(search);
      out.write("\">대전·충청</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=");
      out.print(category);
      out.write("&location=L5&search=");
      out.print(search);
      out.write("\">대구·경북</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=");
      out.print(category);
      out.write("&location=L6&search=");
      out.print(search);
      out.write("\">부산·경남</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=");
      out.print(category);
      out.write("&location=L7&search=");
      out.print(search);
      out.write("\">울산</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=");
      out.print(category);
      out.write("&location=L8&search=");
      out.print(search);
      out.write("\">광주</a></li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"rightWrapper\">\r\n");
      out.write("\t\t<h3>미플 모임</h3>\r\n");
      out.write("\t\t<div id=\"search\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"\" id=\"searchKeyword2\" placeholder=\"검색할 키워드를 입력하세요!\"/>\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"searchBtn\">검색</button>\r\n");
      out.write("\t\t\t");
if(loginMember != null){ 
      out.write("\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"createMeeting\" onclick=\"createMeeting();\">모임생성</button>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
if(list.isEmpty()==false && list!=null){ 
      out.write("\r\n");
      out.write("\t\t<div class=\"boxWrapper\">\r\n");
      out.write("\t\t");
int i=0; int loop=list.size() >=3 ? 3 : list.size(); 
      out.write("\r\n");
      out.write("\t\t");
for(;i<loop;i++) { 
      out.write("\r\n");
      out.write("\t\t");
 
			Calendar now = Calendar.getInstance();
			now = new GregorianCalendar(now.get(Calendar.YEAR),now.get(Calendar.MONTH), now.get(Calendar.DATE));
			
			Calendar mDay = Calendar.getInstance();
			mDay.setTimeInMillis(list.get(i).getTime().getTime());
			mDay = new GregorianCalendar(mDay.get(Calendar.YEAR),mDay.get(Calendar.MONTH), mDay.get(Calendar.DATE));
			
			long mil2 = mDay.getTimeInMillis();
			long mil1 = now.getTimeInMillis();
			int diff = (int)((double)(mil2-mil1)/(1000*60*60*24));
			String dDay;
			if(diff>0){
				dDay="D-"+Integer.toString(diff);
			}else if(diff==0){
				dDay="D-Day!";
			}else{
				dDay="종료";
			}
		
      out.write("\r\n");
      out.write("\t\t\t<div class=\"boxContents\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath()+"/meeting/meetingView?no="+list.get(i).getMeetingNo());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/");
      out.print(list.get(i).getAttach().getRenamedFilename() );
      out.write("\" width=220px height=150px/>\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(list.get(i).getTitle() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<span id=\"dDay\">");
      out.print(dDay );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"boxWrapper\">\r\n");
      out.write("\t\t");
loop=list.size() >=6 ? 6 : list.size(); 
      out.write("\r\n");
      out.write("\t\t");
for(;i<loop;i++) { 
      out.write("\r\n");
      out.write("\t\t");
 
			Calendar now = Calendar.getInstance();
			now = new GregorianCalendar(now.get(Calendar.YEAR),now.get(Calendar.MONTH), now.get(Calendar.DATE));
			
			Calendar mDay = Calendar.getInstance();
			mDay.setTimeInMillis(list.get(i).getTime().getTime());
			mDay = new GregorianCalendar(mDay.get(Calendar.YEAR),mDay.get(Calendar.MONTH), mDay.get(Calendar.DATE));
			
			long mil2 = mDay.getTimeInMillis();
			long mil1 = now.getTimeInMillis();
			int diff = (int)((double)(mil2-mil1)/(1000*60*60*24));
			String dDay;
			if(diff>0){
				dDay="D-"+Integer.toString(diff);
			}else if(diff==0){
				dDay="D-Day!";
			}else{
				dDay="종료";
			}
		
      out.write("\r\n");
      out.write("\t\t\t<div class=\"boxContents\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath()+"/meeting/meetingView?no="+list.get(i).getMeetingNo());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/");
      out.print(list.get(i).getAttach().getRenamedFilename() );
      out.write("\" width=220px height=150px/>\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(list.get(i).getTitle() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<span id=\"dDay\">");
      out.print(dDay );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"boxWrapper\">\r\n");
      out.write("\t\t");
loop=list.size() >=9 ? 9 : list.size(); 
      out.write("\r\n");
      out.write("\t\t");
for(;i<loop;i++) { 
      out.write("\r\n");
      out.write("\t\t");
 
			Calendar now = Calendar.getInstance();
			now = new GregorianCalendar(now.get(Calendar.YEAR),now.get(Calendar.MONTH), now.get(Calendar.DATE));
			
			Calendar mDay = Calendar.getInstance();
			mDay.setTimeInMillis(list.get(i).getTime().getTime());
			mDay = new GregorianCalendar(mDay.get(Calendar.YEAR),mDay.get(Calendar.MONTH), mDay.get(Calendar.DATE));

			long mil2 = mDay.getTimeInMillis();
			long mil1 = now.getTimeInMillis();
			int diff = (int)((double)(mil2-mil1)/(1000*60*60*24));
			String dDay;
			if(diff>0){
				dDay="D-"+Integer.toString(diff);
			}else if(diff==0){
				dDay="D-Day!";
			}else{
				dDay="종료";
			}
			
		
      out.write("\r\n");
      out.write("\t\t\t<div class=\"boxContents\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath()+"/meeting/meetingView?no="+list.get(i).getMeetingNo());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/");
      out.print(list.get(i).getAttach().getRenamedFilename() );
      out.write("\" width=220px height=150px/>\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(list.get(i).getTitle() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<span id=\"dDay\">");
      out.print(dDay );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t<h1 style=\"line-height: 500px;\">조회결과가 없습니다</h1>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t<div id='pageBar'>\r\n");
      out.write("\t\t\t");
      out.print( request.getAttribute("pageBar") != null ? request.getAttribute("pageBar") : "");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<style>\r\n");
      out.write("\t\t.boxWrapper{\r\n");
      out.write("\t\t\twidth:900px;\r\n");
      out.write("\t\t\theight:194px;\r\n");
      out.write("\t\t\tdisplay: flex;\r\n");
      out.write("\t\t\ttransition-duration: 1s;\r\n");
      out.write("\t\t\ttransition-timing-function: ease;\r\n");
      out.write("\t\t\tmargin:0 auto;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.boxContents{\r\n");
      out.write("\t\t\tposition:relative;\r\n");
      out.write("\t\t\twidth:220px;\r\n");
      out.write("\t\t\theight:150px;\r\n");
      out.write("\t\t\tmargin:40px;\r\n");
      out.write("\t\t\tpadding:0;\r\n");
      out.write("\t\t\tborder:2px solid black;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\tbackground:black;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.boxContents:hover{\r\n");
      out.write("\t\t\tanimation-name: ani;\r\n");
      out.write("\t\t\tanimation-duration: 0.5s;\r\n");
      out.write("\t\t\tanimation-iteration-count: infinite;\r\n");
      out.write("\t\t\tanimation-timing-function: ease;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.boxContents:hover span{\r\n");
      out.write("\t\t\tcolor:black;\r\n");
      out.write("\t\t\ttext-shadow: -2px 0 white, 0 2px white, 2px 0 white, 0 -2px white;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t@keyframes ani{\r\n");
      out.write("\t\t\t0%{\r\n");
      out.write("\t\t\t\ttransform: scale(1, 1);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t50%{\r\n");
      out.write("\t\t\t\ttransform: scale(1.1, 1.1);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t100%{\r\n");
      out.write("\t\t\t\ttransform: scale(1, 1);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.boxContents span{\r\n");
      out.write("\t\t\tposition:absolute;\r\n");
      out.write("\t\t\tbottom:8px;\r\n");
      out.write("\t\t\tright:8px;\r\n");
      out.write("\t\t\tcolor:white;\r\n");
      out.write("\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\ttext-shadow: -2px 0 black, 0 2px black, 2px 0 black, 0 -2px black;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dDay{\r\n");
      out.write("\t\t\ttop:8px;\r\n");
      out.write("\t\t\tright:8px;\r\n");
      out.write("\t\t\tcolor:red;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.boxContents img{\r\n");
      out.write("\t\t\tborder-radius: 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tsection{\r\n");
      out.write("\t\t\toverflow: hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#search{\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tright:10px;\r\n");
      out.write("\t\t\ttop:21px;\r\n");
      out.write("\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t//searchKeyword, searchBtn\r\n");
      out.write("\t$(\"#searchBtn\").click(function(){\r\n");
      out.write("\t\tvar keyword = $(\"#searchKeyword2\").val();\r\n");
      out.write("\t\tconsole.log(keyword);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=");
      out.print(category);
      out.write("&location=");
      out.print(location);
      out.write("&search=\"+keyword;\r\n");
      out.write("\t});\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t");
 if(search.length()!=0) {
      out.write("\r\n");
      out.write("\t\t\t$(\"#searchKeyword\").val(\"");
      out.print(search);
      out.write("\");\r\n");
      out.write("\t\t\t$(\"#searchKeyword2\").val(\"");
      out.print(search);
      out.write("\");\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t//모임생성\r\n");
      out.write("\tfunction createMeeting(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingEnroll\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#listWrapper{\r\n");
      out.write("\twidth:1200px;\r\n");
      out.write("\tdisplay:flex;\r\n");
      out.write("}\r\n");
      out.write("#leftWrapper{\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("\theight:800px;\r\n");
      out.write("\tmargin-left:50px;\r\n");
      out.write("\tborder:1px solid red;\r\n");
      out.write("}\r\n");
      out.write("#rightWrapper{\r\n");
      out.write("\tclear:both;\r\n");
      out.write("\twidth:900px;\r\n");
      out.write("\tmin-height: 800px;\r\n");
      out.write("\tborder:1px solid red;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("#leftWrapper ol{\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding-left:30px;\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("}\r\n");
      out.write("#leftWrapper ol li{\r\n");
      out.write("\tmargin-bottom:20px;\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pageBar{\r\n");
      out.write("\theight:50px;\r\n");
      out.write("\tmargin-top:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pageBar span{\r\n");
      out.write("    border-radius: 15%;\r\n");
      out.write("    padding: 9px 15px;\r\n");
      out.write("    background-color: skyblue;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("#pageBar a{\r\n");
      out.write("\tborder-radius: 15%;\r\n");
      out.write("    padding: 9px 15px;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pageBar a:hover{\r\n");
      out.write("    background-color: skyblue;\r\n");
      out.write("    color: white;\r\n");
      out.write("    transition: all ease 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pageBar a:active{\r\n");
      out.write("    background-color: skyblue;\r\n");
      out.write("    color: gray;\r\n");
      out.write("}\r\n");
      out.write("#search{\r\n");
      out.write("\tdisdplay:flex;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/footer.css\" />\r\n");
      out.write("</section>\r\n");
      out.write("<footer>\r\n");
      out.write("        <div class=\"meeple-footer container\">\r\n");
      out.write("        <div class=\"infofooter\">\r\n");
      out.write("            <h1>MeetPeople 제작 정보</h1>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <p>MeetPeople</p>\r\n");
      out.write("            <p>소속 : KH정보교육원 | 서울특별시 강남구 역삼동 823-25</p>\r\n");
      out.write("            <p>팀장 : 김윤수</p>\r\n");
      out.write("            <p>팀원 : 천호현 강종성 박요한 이승우 최한성</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"etc\">\r\n");
      out.write("            <h1>관련 사이트</h1>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <p>김윤수 : <a href=\"https://github.com/kimdia200\">https://github.com/kimdia200 <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("            <p>박요한 : <a href=\"https://github.com/dygksqkr12\">https://github.com/dygksqkr12 <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("            <p>천호현 : <a href=\"https://github.com/hohyuncheon\">https://github.com/hohyuncheon <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("            <p>강종성 : <a href=\"https://github.com/bellcastle88\">https://github.com/bellcastle88 <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("            <p>최한성 : <a href=\"https://github.com/HSdover\">https://github.com/HSdover <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("            <p>프로그래머스 : <a href=\"https://programmers.co.kr/\">https://programmers.co.kr <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"contact\">\r\n");
      out.write("            <h1>고객센터</h1>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/claim/claimMenu\">문의하기 <i class=\"fas fa-external-link-alt\"></i></a>\r\n");
      out.write("            <p>Tel : 010-6353-4583 (평일 09:00 ~ 18:00)</p>\r\n");
      out.write("            <p>Mail : dover0601@naver.com</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"last\">\r\n");
      out.write("        <hr id=\"lasthr\">\r\n");
      out.write("        <h2 id=\"last\">Copyright 2021. &lt; KH-SEMI-PROJECT &gt; all rights reserved.</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script \r\n");
      out.write("     src=\"https://kit.fontawesome.com/39a2f80180.js\"\r\n");
      out.write("     crossorigin=\"anonymous\"\r\n");
      out.write("     ></script>\r\n");
      out.write("</footer>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
